version: '3.8'

services:
  user-manager:
    build: . # referenziert Dockerfile in selber Struktur
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/user_manager_db
    networks:
      - book-network
    
  mongodb:
    image: mongo:latest
    networks:
    - book-network

  proxy:
    image: nginx:1.21
    ports:
      - "82:82"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - user-manager
    networks:
      - book-network

      
networks:
  book-network:
    external: true # self-managed network (needs to be created manually before)
#  public-net:
#  db-net: