apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-manager
  template:
    metadata:
      labels:
        app: user-manager
    spec:
      containers:
      - name: user-manager
        image: docker.io/cybun/user-manager:latest
        ports:
        - containerPort: 8081


## Notiz für Conni morgen: Folgender Fehler wird bei Image Pull angezeigt:
## PS C:\Users\Alia\StudioProjects\user-manager\usermanager> docker pull user-manager:latest
##>>a

## Error response from daemon: pull access denied for user-manager, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
## Nach login: ImagePullBackOff